str1 = input("Please enter one number: ")
str2 = input("Please enter another number: ")
print()
print("You entered:")
print("str1:",str1)
print("str2:",str2)
print()
print("Type of str1:",type(str1))
print("Type of str2:",type(str2))
print()
print("Changing the type to int:")
str1 = int(str1)
str2 = int(str2)
print("Type of str1:",type(str1))
print("Type of str2:",type(str2))
