import os
os.system("clear")
print("Hello!")
print()
print("Did you know? Phrases are strings of characters.")
print("Yes, including whitespaces etc.")
print("But to print \" you need to use the \\ escape character.")
print()
str1 = input("Please enter a phrase: ")
print()
print("You entered:",str1)
print("Name of var: str1")
print("Var type:",type(str1))
print()
print("The first character of your string is:",str1[0])
print("The last character of your string is:",str1[-1])
print()
print("Now trying range of characters:")
print("[0:1]:",str1[0:1])
print("[0:2]:",str1[0:2])
print("[0:3]:",str1[0:3])
print("[0:4]:",str1[0:4])
print("[0:5]:",str1[0:5])
print("[0:6]:",str1[0:6])
print()
print("Omitting the start, means 0:")
print("[:1]:",str1[:1])
print("[:2]:",str1[:2])
print("[:3]:",str1[:3])
print("[:4]:",str1[:4])
print("[:5]:",str1[:5])
print("[:5]:",str1[:6])
print()
