import os
os.system("clear")
print("Hello!")
print()
print("========================================")
print("Creating a list of:")
print("a letter, a number, a word and a phrase.")
print("----------------------------------------")
list1 = ["H", 2, "Hello", "My name is Diamantis."]
print(list1)
print("Type of list1:",type(list1))
print()
print("========================================")
print("Demonstrating list indexing:")
print("----------------------------------------")
print("list1[0]:",list1[0])
print("list1[1]:",list1[1])
print("list1[2]:",list1[2])
print("list1[3]:",list1[3])
print()
print("========================================")
print("Demonstrating indexing range for lists:")
print("----------------------------------------")
print("list1[0:1]:",list1[0:1])
print("list1[0:2]:",list1[0:2])
print("list1[:2] :",list1[:2])
print("list1[0:3]:",list1[0:3])
print("list1[0:4]:",list1[0:4])
print()
print("===========================================")
print("Each member of a list has its own data type")
print("-------------------------------------------")
print("Type of list1[0]:",type(list1[0]))
print("Type of list1[1]:",type(list1[1]))
print("Type of list1[2]:",type(list1[2]))
print("Type of list1[3]:",type(list1[3]))
print()
