import os
os.system("clear")
print("Hello!")
print("===========================================================")
print("Demonstrations of tuples. (Non mutable var.)")
print("***********************************************************")
print()
print("Creating a tuple with a word, an int, a float and a phrase.")
print("-----------------------------------------------------------")
tup1 = ("Hello", 2, 3.1415926535, "My name is Diamantis.")
print(tup1)
print("Type of tup1:",type(tup1))
print()
print("===========================================================")
print("Demonstrating indexing in tuples.")
print("-----------------------------------------------------------")
print("tup1[0]:",tup1[0])
print("tup1[1]:",tup1[1])
print("tup1[2]:",tup1[2])
print("tup1[3]:",tup1[3])
print()
print("===========================================================")
print("Demonstrating indexing range with tuples.")
print("-----------------------------------------------------------")
print("tup1[:1] :",tup1[:1])
print("tup1[:2] :",tup1[:2])
print("tup1[1:2]:",tup1[1:2])
print("tup1[1:4]:",tup1[1:4])
print()
print("===========================================================")
print("Data types of tuple contents.")
print("-----------------------------------------------------------")
print("Type of tup1[0]:",type(tup1[0]))
print("Type of tup1[1]:",type(tup1[1]))
print("Type of tup1[2]:",type(tup1[2]))
print("Type of tup1[3]:",type(tup1[3]))
print()
print("===========================================================")
print("Printing size of various tuples.")
print("-----------------------------------------------------------")
tp1=("Hello")
tp2=("Hello World!")
tp3=("Hello", 2)
tp4=("Hello", 2, 3.1415926535)
print("Tuple 1:",tp1,"\t\t\t\tSize of:",tp1.__sizeof__())
print("Tuple 2:",tp2,"\t\t\tSize of:",tp2.__sizeof__())
print("Tuple 3:",tp3,"\t\t\tSize of:",tp3.__sizeof__())
print("Tuple 4:",tp4,"\tSize of:",tp4.__sizeof__())
print()
