print("Hello!")
name = input("Please enter your name: ")
age = input("Please enter your age: ")
print()
print("Hello",name,"!")
print("You are a tender",age,"years old!")
print("10 years ago you were",int(age)-10,"years old!")
print("In 10 years you will be",int(age)+10,"years old!")
