print()
print("==================================================")
print("********** ╔═╗  ╔═╗  ╔╦╗  ╔╦╗  ╔═╗  ╔═╗ **********")
print("********** ╠═╝  ║╣   ║║║   ║║  ╠═╣  ╚═╗ **********")
print("********** ╩    ╚═╝  ╩ ╩  ═╩╝  ╩ ╩  ╚═╝ **********")
print("==================================================")
print("In Python, the order of execution of mathematical")
print("operators follows the\"PEMDAS\" rule:")
print("--------------------------------------------------")
print()
print("1. Parentheses")
print("2. Exponents")
print("3. Multiplications")
print("4. Divisions")
print("5. Additions")
print("6. Subtractions")
print()
