import os
os.system("clear")
print("============================================")
print("****** ╔═╗╦╦  ╦ ╦ ╦  ╔═╗╔╦╗╦═╗╦╔╗╔╔═╗ ******")
print("****** ╚═╗║║  ║ ╚╦╝  ╚═╗ ║ ╠╦╝║║║║║ ╦ ******")
print("****** ╚═╝╩╩═╝╩═╝╩   ╚═╝ ╩ ╩╚═╩╝╚╝╚═╝ ******")
print("============================================")
print()
phrase = input("Hello! Please enter a phrase: ")
print()
phrase = phrase.replace("a", "i")
phrase = phrase.replace("e", "i")
phrase = phrase.replace("o", "i")
phrase = phrase.replace("u", "i")
phrase = phrase.replace("y", "i")
print(phrase)
